apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sou-autores-app
  labels:
    app: sou-autores-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sou-autores-app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: sou-autores-app
    spec:
      volumes:
        - name: sou-autores-app-volume
          emptyDir: {}
        - name: nginx-config-volume
          configMap:
            name: nginx-config
      hostAliases:
        - ip: "127.0.0.1"
          hostnames:
            - "backend"
      initContainers:
        - name: app
          image: us.gcr.io/univesp-201808/sou-contrata:1.0.24qa
          command: ['/bin/sh', '-c', 'cp -rp /var/www/* /app/']
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 150m
              memory: 256Mi
            requests:
              cpu: 150m
              memory: 256Mi
          volumeMounts:
            - name: sou-autores-app-volume
              mountPath: /app
          envFrom:
            - secretRef:
                name: sou-autores-app-secrets
      containers:
        - name: php-fpm
          image: us.gcr.io/univesp-201808/php-fpm:7.2.3
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 150m
              memory: 256Mi
            requests:
              cpu: 150m
              memory: 256Mi
          ports:
            - containerPort: 9000
          volumeMounts:
            - name: sou-autores-app-volume
              mountPath: /var/www
          envFrom:
            - secretRef:
                name: sou-autores-app-secrets
        - name: nginx
          image: nginx:latest
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 100m
              memory: 64Mi
            requests:
              cpu: 100m
              memory: 64Mi
          ports:
            - containerPort: 80
          volumeMounts:
            - name: sou-autores-app-volume
              mountPath: /var/www
            - name: nginx-config-volume
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
